from .auto_refresh import maybe_autorefresh
from .meta_kpis_grid import render_meta_kpis_grid
from .performance_panel import render_performance_panel
from .welfare_risk_panel import render_welfare_risk_panel
from .sensor_values_panel import render_sensor_values_panel
from .audio_events_panel import render_audio_events_panel
from .detections_table import render_detections_table
from .live_camera_view import render_live_camera_view
from .explainability_panel import render_explainability_panel
from .alert_center_panel import render_alert_center_panel


